version: '3'
services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: book-manager-frontend
    depends_on:
      - backend
    container_name: book-manager-frontend
    ports:
      - 8080:80
    networks:
      - book-manager-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: book-manager-backend
    container_name: book-manager-backend
    ports:
      - 3000:3000
    networks:
      - book-manager-network

networks:
  book-manager-network:
    driver: bridge